### ISSUE TITLE
universal-redux example broken

### ISSUE THREAD

**Issue by Falieson** [4Catalyzer/found#88]
Steps To Reproduce
======
I'm guessing the solution for both these problems centers around a correct .babelrc in the universal-redux folder

Problem 1
------
```
$ git clone 4Catalyzer/found
$ cd found/examples/universal-redux
$ npm install
$ npm start
$ babel-node src/server
/Users/florian.mettetal/Code/.private/found/examples/universal-redux/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180
          throw new ReferenceError(messages.get("pluginUnknown", plugin, loc, i, dirname));
          ^

ReferenceError: Unknown plugin "dev-expression" specified in "/Users/florian.mettetal/Code/.private/found/.babelrc" at 0, attempted to resolve relative to "/Users/florian.mettetal/Code/.private/found"
    at /Users/florian.mettetal/Code/.private/found/examples/universal-redux/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (native)
    at Function.normalisePlugins (/Users/florian.mettetal/Code/.private/found/examples/universal-redux/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/florian.mettetal/Code/.private/found/examples/universal-redux/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/florian.mettetal/Code/.private/found/examples/universal-redux/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at compile (/Users/florian.mettetal/Code/.private/found/examples/universal-redux/node_modules/babel-register/lib/node.js:103:45)
    at loader (/Users/florian.mettetal/Code/.private/found/examples/universal-redux/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/florian.mettetal/Code/.private/found/examples/universal-redux/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
error Command failed with exit code 1.
```

Problem 2
------
```
$ git clone 4Catalyzer/found
$ cd found/
$ rm .babelrc
$ cd examples/universal-redux
$ npm install
$ npm start
$ babel-node src/server
SyntaxError: /Users/florian.mettetal/Code/.private/ultimate-react/src/server.js: Unexpected token (86:6)
  84 |     .status(renderArgs.error ? renderArgs.error.status : 200)
  85 |     .send(renderPageToString(
> 86 |       <Provider store={store}>
     |       ^
  87 |         <RouterProvider router={renderArgs.router}>
  88 |           {render(renderArgs)}
  89 |         </RouterProvider>
    at Parser.pp$5.raise (/Users/florian.mettetal/Code/.private/ultimate-react/node_modules/babylon/lib/index.js:4454:13)
```

**Comment by taion** [comment]
npm@5 and Yarn don't like how I set up the links. I fixed it a few days ago with https://github.com/4Catalyzer/found/pull/87, so just pull again.

**Comment by Falieson** [comment]
When I made this issue I was using yarn19, npm4 - I've upgraded everything to latest (yarn24.6, npm5) and restarted, did a fresh clone, top of my git history is 8dcd8

```
~/Code//found/examples/universal-redux (master●)
$ npm start

> universal-redux@0.1.0 start /Users/florian.mettetal/Code/.private/found/examples/universal-redux
> babel-node src/server

/Users/florian.mettetal/Code/.private/found/examples/universal-redux/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180
          throw new ReferenceError(messages.get("pluginUnknown", plugin, loc, i, dirname));
          ^

ReferenceError: Unknown plugin "dev-expression" specified in "/Users/florian.mettetal/Code/.private/found/.babelrc" at 0, attempted to resolve relative to "/Users/florian.mettetal/Code/.private/found"
    at /Users/florian.mettetal/Code/.private/found/examples/universal-redux/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (native)
    at Function.normalisePlugins (/Users/florian.mettetal/Code/.private/found/examples/universal-redux/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/florian.mettetal/Code/.private/found/examples/universal-redux/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/florian.mettetal/Code/.private/found/examples/universal-redux/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at compile (/Users/florian.mettetal/Code/.private/found/examples/universal-redux/node_modules/babel-register/lib/node.js:103:45)
    at loader (/Users/florian.mettetal/Code/.private/found/examples/universal-redux/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/florian.mettetal/Code/.private/found/examples/universal-redux/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
```


**(same as before) After deleting .babelrc**
```
$ npm start

> universal-redux@0.1.0 start /Users/florian.mettetal/Code/.private/found/examples/universal-redux
> babel-node src/server

/Users/florian.mettetal/Code/.private/found/examples/universal-redux/node_modules/babel-core/lib/transformation/file/index.js:590
      throw err;
      ^

SyntaxError: /Users/florian.mettetal/Code/.private/found/examples/universal-redux/src/server.js: Unexpected token (86:6)
  84 |     .status(renderArgs.error ? renderArgs.error.status : 200)
  85 |     .send(renderPageToString(
> 86 |       <Provider store={store}>
     |       ^
  87 |         <RouterProvider router={renderArgs.router}>
  88 |           {render(renderArgs)}
  89 |         </RouterProvider>
    at Parser.pp$5.raise (/Users/florian.mettetal/Code/.private/found/examples/universal-redux/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/Users/florian.mettetal/Code/.private/found/examples/universal-redux/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp$3.parseExprAtom (/Users/florian.mettetal/Code/.private/found/examples/universal-redux/node_modules/babylon/lib/index.js:3750:12)
    at Parser.pp$3.parseExprSubscripts (/Users/florian.mettetal/Code/.private/found/examples/universal-redux/node_modules/babylon/lib/index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (/Users/florian.mettetal/Code/.private/found/examples/universal-redux/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/Users/florian.mettetal/Code/.private/found/examples/universal-redux/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/Users/florian.mettetal/Code/.private/found/examples/universal-redux/node_modules/babylon/lib/index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (/Users/florian.mettetal/Code/.private/found/examples/universal-redux/node_modules/babylon/lib/index.js:3344:19)
    at Parser.pp$3.parseExprListItem (/Users/florian.mettetal/Code/.private/found/examples/universal-redux/node_modules/babylon/lib/index.js:4312:16)
    at Parser.pp$3.parseCallExpressionArguments (/Users/florian.mettetal/Code/.private/found/examples/universal-redux/node_modules/babylon/lib/index.js:3573:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! universal-redux@0.1.0 start: `babel-node src/server`
npm ERR! Exit status 1
npm ERR!
```

**Comment by taion** [comment]
Oh, interesting. I guess it only works because I have `node_modules` installed in the repo root. One sec.

**Comment by Falieson** [comment]
@taion THANK YOU!!!
